### ISSUE TITLE
Thumbnail images not loading within Canvas

### ISSUE THREAD

**Issue by apell74** [learn-co-curriculum/dsc-bayes-theorem#2]
## Link to Canvas
https://learning.flatironschool.com/courses/6222/pages/bayes-theorem?module_item_id=529304

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [x ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

## Describe the Issue
Canvas is not rendering thumbnail images for any lessons on my computer. This includes formulae and variables.
### Source

```

```

## What OS Are You Using?

- [ x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Hello. Thank you for bringing this to our attention. The Bayes material is now legacy material, so we are not currently updating it. Thus, to see all of the formulas render nicely, please look at the repo:
https://github.com/learn-co-curriculum/dsc-bayes-theorem
